login/urls.py
from django.urls import path, include
from django.contrib import admin
from products import views
from . import views

urlpatterns = [
    #Добавление продукта в заказ
    path('login/add',views.add, name = 'add'),

    #Добавление продукта в каталог
    path('login/add_product',views.add_product, name = 'add_product'),
    path('login/', views.login, name='login'),
    path('login/out/', views.out, name= 'out'),

]

products/urls.py
from django.urls import path, include
from django.contrib import admin
from products import views

urlpatterns = [
    # url(r'^landing123/', views.landing, name='landing'),
    path('product/<product_id>/', views.product, name='product'),
]

sayt1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', include('beautysaves.urls')),
    path('', include('products.urls')),
    path('', include('favorite.urls')),
    path('', include('login.urls')),
] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категория товаров'

class Product(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    category = models.ForeignKey(ProductCategory,on_delete=models.PROTECT,blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    description = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class ProductImage(models.Model):
    product = models.ForeignKey(Product,on_delete=models.PROTECT, blank=True, null=True, default=None)
    image = models.ImageField(upload_to='media/')
    is_active = models.BooleanField(default=True)
    is_main = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

products/forms.py
from django import forms
from products.models import ProductImage, Product


class NewProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'price')

class NewProductImageForm(forms.ModelForm):
    class Meta:
        model = ProductImage
        fields = ('product', 'image')

products/views.py
from django.shortcuts import render
from products.models import *
from favorite import models as FavModels


def product(request, product_id):
    product = Product.objects.get(id=product_id)

    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()
        print(request.session.session_key)

    try:
        if request.COOKIES.get("id_user") != 'None':
            print("cookie work")
            is_login = True
        else:
            is_login = False
    except:
        is_login = False

    id_user = request.COOKIES.get('id_user')
    products = FavModels.ProductInBasket.objects.filter(session_key=id_user)
    products_total_nmb = products.count()

    product.id = product.id
    product.name = product.name
    product.price = product.price
    is_login = True
    is_admin=False

    return render(request, 'products/products.html', locals())

templates/products/products.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                {% for image_item in product.productimage_set.all %}
                    <div class="product-image-item">
                        <img src="{{ image_item.image.url }}" class="img-responsive">
                    </div>
                {% endfor %}
            </div>
            <div class="col-lg-6">
                <h1 class="text-center">
                    {{ product.name }}
                </h1>
                <div class="">
                    <p>
                        Price: {{ product.price }}
                    </p>
                </div>
                <div>
                      <!-- Nav tabs -->
                      <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#description" aria-controls="home" role="tab" data-toggle="tab">
                                Описание
                            </a>
                        </li>
{#                        <li role="presentation">#}
{#                            <a href="#delivery" aria-controls="profile" role="tab" data-toggle="tab">#}
{#                                Доставка#}
{#                            </a>#}
{#                        </li>#}
{#                        <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>#}
{#                        <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>#}
                      </ul>

                      <!-- Tab panes -->
                      <div class="tab-content product-description-tabs">
                        <div role="tabpanel" class="tab-pane active" id="description">
                            {{ product.description }}
                        </div>
                        <div role="tabpanel" class="tab-pane" id="delivery">
                            <h3>Как мы делаем доставку</h3>
                        </div>
                        <div role="tabpanel" class="tab-pane" id="messages">...</div>
                        <div role="tabpanel" class="tab-pane" id="settings">...</div>
                      </div>
                </div>

                    <form method="post"   action="/basket_adding">
                        {% csrf_token %}
                        Выберите размер:
                        <input type="number" class="form-control" name="number" id="number">

                        <input type="hidden" name="product_id" value="{{ product.id }}">

                        <input type="submit" id="submit_btn" class="btn btn-danger" value="Добавить">


                        <!--class="form-inline"-->

                        <!--
                                <form action="" >
                                    <input type="submit"  id="submit_btn" class="btn btn-danger"
                                    data-product_id = "{{ product.id }}"
                                    data-name ="{{ product.name }}"
                                    data-price ="{{ product.price }}" value="Мой фаворит">
                                </form>
                           -->



                    </form>

            </div>
        </div>
    </div>
{% endblock %}